name: Build Release

on:
    push:
        tags:
            - '*'

jobs:
    build_release:
        name: "Build a release"
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Go Environment
              uses: actions/setup-go@v5
              with:
                go-version: '1.22.x'
            - name: Get dependencies
              run: make get-deps
            - name: Build Linux AMD64
              run: make build-linux-amd64
            - name: Build Linux ARM64
              run: make build-linux-arm64
            - name: Build Windows AMD64
              run: make build-windows-amd64
            - name: Archive customization files
              run: zip -r bin/customizations.zip customizations/*
            - name: Create release
              uses: ncipollo/release-action@v1
              with:
                artifacts: "bin/*"
                generateReleaseNotes: true

            