name: Test Build

on:
    pull_request:
      types: [opened, synchronize, reopened]

jobs:
    Test-Build:
        name: "Try building the project"
        runs-on: ubuntu-latest
        permissions:
            checks: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  fetch-tags: true
            - name: Setup Go Environment
              uses: actions/setup-go@v5
              with:
                go-version: '1.22.x'
            - name: Get dependencies
              run: make get-deps
            - name: Build Linux AMD64
              run: make build-linux-amd64